[package]
name = "angusjf-blog"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-cmark = "0.9.2"
chrono = "0.4"
tinytemplate = "1.2"
serde_derive = "1.0.147"
serde = "1.0.147"
serde_yaml = "0.9"
thumbhash = "0.1.0"
image = "0.24.6"
base64 = "0.21.0"
