#!/bin/bash

set -e

rm -rf dist
mkdir dist
cp -r public/* dist/

CANONICAL_ORIGIN="https://angusjf.com"

cards=()

for file in content/blog/*.md
do
    id="$(basename ${file%.md})"

    echo "- /$id"

    mkdir dist/$id

    cat $file \
        | sed -n '1,/^---$/ { /^---$/d; p; }'\
        | jq --arg path "/$id" --arg html "$(cat $file | sed -e '1,/^---$/d' $file | markdown)" '. + {path: $path, html: $html}' \
        | jq "{
                img_url: .img_url,
                img_alt: .img_alt,
                canonical_origin: \"$CANONICAL_ORIGIN\",
                path: .path,
                description: .seo_description,
                title: .title,
                index: null,
                blog: { content: .html, date: .date }
            }" \
        | $PLATELET templates/root.html > dist/$id/index.html &

    cards+=$(cat $file | sed -n '1,/^---$/ { /^---$/d; p; }' | jq --arg path "/$id" '.links_to = $path')
done

echo "- /"

cards+=$( cat content/experiments/*.json | jq '.links = .urls | .links_to = .urls[0].href' )

echo "${cards[*]}" \
| jq -s --argjson me "$(cat me.json)" 'sort_by(.date) | reverse | [$me] + . | map(.content = .summary)' \
| jq "{
        img_url: \"/images/plants.webp\",
        img_alt: \"Angus Findlay\",
        canonical_origin: \"$CANONICAL_ORIGIN\",
        path: \"\",
        description: \"Angus Findlay's Blog - angusjf\",
        title: \"Angus Findlay\",
        index: { cards: . },
        blog: null
      }" | $PLATELET templates/root.html > dist/index.html # | cargo run
